var myNum;
myNum = 2;
console.log(myNum);
var myStr;
myStr = "Hello World";
console.log(myStr);
var myBool;
myBool = true;
console.log(myBool);
var myAnyType;
myAnyType = "Hello";
console.log(myAnyType);
var arrBool;
arrBool = [true, false];
console.log(arrBool);
var myChar;
myChar = "Learning type assertion";
console.log(myChar.length);
